controller_list:
  - name: fake_arm_controller
    joints:
      - motortom2m
      - joint2
      - joint4
      - joint6
  - name: fake_end_controller
    joints:
      - end
initial:  # Define initial robot poses.
  - group: arm
    pose: armhome
  - group: end
    pose: endhome